# ASP.NET Core (.NET Framework)
# Build and test ASP.NET Core projects targeting the full .NET Framework.
# Add steps that publish symbols, save build artifacts, and more:
# https://docs.microsoft.com/azure/devops/pipelines/languages/dotnet-core

trigger:
- none

pool:
  vmImage: 'windows-latest'

stages:  
- stage: Build  
  jobs:  
  - job: BuildJob  
    steps:  
    - checkout: self
    - task: DotNetCoreCLI@2
      inputs:
        command: 'restore'
        projects: '**/*.csproj'
        feedsToUse: 'select'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'build'
        projects: '**/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
  - job: Test
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'test'
        projects: '**/*UnitTests/*.csproj'
        arguments: '--configuration $(BuildConfiguration)'
  - job: Publish
    steps:
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: true
        arguments: '--configuration $(BuildConfiguration) --output "$(build.artifactstagingdirectory)"'
    - task: DotNetCoreCLI@2
      inputs:
        command: 'publish'
        publishWebProjects: false
        projects: '**/*FunctionalTest*.csproj'
        arguments: '--configuration $(BuildConfiguration) --output "$(build.artifactstagingdirectory)/FunctionalTests"'
        zipAfterPublish: false
        modifyOutputPath: false
  - job: CopyFiles
    steps:
    - task: CopyFiles@2
      inputs:
        SourceFolder: 'Application/aspnet-core-dotnet-core.FunctionalTests'
        Contents: '**/*.runsettings'
        TargetFolder: '$(Build.ArtifactStagingDirectory)/FunctionalTests'
  - job: PublishArtifacts
    steps:
    - task: PublishBuildArtifacts@1
      inputs:
        PathtoPublish: '$(Build.ArtifactStagingDirectory)'
        ArtifactName: 'drop'
        publishLocation: 'Container'
- stage: Staging
  jobs:  
  - job: TestOne  
    steps:  
    - script: echo Test One  
  - job: TestTwo 
    steps:  
    - script: echo Test Two  
- stage: Production
  jobs:  
  - job: TestOne  
    steps:  
    - script: echo This is a production  
  - job: TestTwo 
    steps:  
    - script: echo This is production Test 2